### ISSUE TITLE
Filebot version

### ISSUE THREAD

**Issue by joss2133** [Neonox31/docker-transmission-openvpn-filebot#2]
Hi, why the filebot version used is not the latest 4.8.5?

Is there a problem with that version?

Thanks

**Comment by Neonox31** [comment]
Hi,

No, just because this is the last version pushed on sourceforge : https://sourceforge.net/projects/filebot/files/filebot/

I have to change the filebot installation method in `Dockerfile` to get the `4.8.5` version.
